export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body style={{margin: 0, padding: 0, fontFamily: 'Poppins'}}>{children}</body>
    </html>
  )
}
