
FROM hivemq/hivemq4:latest

COPY --chown=hivemq:hivemq ./config/kafka-extension/config.xml /opt/hivemq/extensions/hivemq-kafka-extension/conf/config.xml
# COPY --chown=hivemq:hivemq ./config/config.xml /opt/hivemq/conf/config.xml

RUN rm -f /opt/hivemq/extensions/hivemq-kafka-extension/DISABLED