name: Tests for Backend

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'backend/**'
      - '.github/workflows/backend_tests.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 'backend/'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Get dependencies
        run: go mod tidy
      - name: Run backend test suite
        run: make tests